server:
    port: 8081

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/jwt_spring
        username: root
        password: q1w2e3r4t5y6
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect